name: Build Android App and Publish to BrowserStack
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for making a new build'
        required: true

jobs:
  checkout-and-build:
    runs-on: ubuntu-latest
    steps:
      # Use GitHub's Checkout Action to pull in code to GITHUB_WORKSPACE
      # https://github.com/actions/checkout
      # https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables
      - uses: actions/checkout@v2
      # Run commands using the shell (which is bash on non-Windows platforms)
      # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsrun
      - name: Generate Local Properties file for Gradle build to use
        with:
          ABLY_API_KEY: ${{ secrets.ABLY_API_KEY }}
        run: |
          echo "build.reason=${{ github.event.inputs.reason }}" > local.properties
          echo "ably.key=$ABLY_API_KEY" >> local.properties
          echo "ably.env=production" >> local.properties
      - name: Generate Google Services file for Gradle build to use
        with:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > google-services.json
        working-directory: app
      - name: Build APK using Gradle
        run: ./gradlew assembleDebug
      - uses: actions/upload-artifact@v2
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
